#!/usr/bin/env python
from utils import color, pathutils, logutils
import preprocessor
import os
import sys
import stat

class OpenRCgen():
    def __init__(self, template=None, *args, **kwargs):
        self.scrpath = "/etc/init.d/"
        self.template = pathutils.templatepath() + "/templates/openrc_initscript.txt"
        if template: self.template = template #I would love to use kwargs here but they dont resort to default value if kwarg is none...

    def OpenRCgen(self, scrpath: str) -> None:
        logutils.good("[+] Generating for OpenRC")
        template_file = open(self.template, 'r')

        template = template_file.read()

        fin = preprocessor.preprocessor.proprocess_template(template, scrpath)
        service_name = preprocessor.preprocessor.get_prog_name(scrpath)
        logutils.good(f"[+] Template filling done ! Creating script in {self.scrpath}{service_name}")

        if os.path.exists(f'{self.scrpath}{service_name}'):
            logutils.red("!!! There is already a script at the path automatially generated by mekanism!!! ")
            ans = input("Owerwrite?: ")
            if ans.lower() not in ("y", "yes"):
                sys.exit(0)


        
        scr = open(f"{self.scrpath}{service_name}", 'w')

        logutils.good(f"[+] Writing generated script to {self.scrpath}{service_name}")
        scr.write(fin)
        scr.close()

        st = os.stat(f"{self.scrpath}{service_name}")
        os.chmod(f"{self.scrpath}{service_name}", st.st_mode | stat.S_IEXEC)


        logutils.good("[+] Init script written successfully! Would you like to check it out? [Y/n]")
        ans = input()

        if ans.lower() in ("y", "yes"):
            scr = open(f"{self.scrpath}{service_name}", 'r')
            print(scr.read())
        


        
