#!/usr/bin/env python

from utils import color, pathutils, logutils
from preprocessor import preprocessor
import os
import stat
import sys

class SystemDgen():
    def __init__(self, template=None, scrpath=None, *args, **kwargs):
        self.scrpath = "/etc/systemd/system/"
        if scrpath: self.scrpath = scrpath
        self.template = pathutils.templatepath() + "/templates/systemd_service.txt" 
        if template: self.template = template #I would love to use kwargs here but they dont resort to default value if kwarg is none...
    def SystemDgen(self, cmd: str, opath: str=None):
        print(color.Colors().brgreen +  "[+] Generating for SystemD" + color.Colors().reset)
        template_file = open(self.template, 'r')

        template = template_file.read()

        fin = preprocessor.proprocess_template(template, cmd)
        service_name = pathutils.get_prog_name(cmd) 

        outpath = f"{self.scrpath}{service_name}"
        if opath is not None: outpath = opath
        

        logutils.good(f"[+] Template filling done ! Creating script in {outpath}")
        if os.path.exists(outpath):
            logutils.red("!!! There is already a script at the path automatially generated by mekanism!!! ")
            ans = input("Owerwrite?: ")
            if ans.lower() not in ("y", "yes"):
                sys.exit(0)

        if outpath.endswith(".service") is not True:
            outpath += ".service"
        scr = open(f"{outpath}", 'w')

        logutils.good(f"[+] Writing generated script to {outpath}")
        scr.write(fin)
        scr.close()

        logutils.good("[+] Init script written successfully! Would you like to check it out? [Y/n]")
        ans = input()

        if ans.lower() in ("y", "yes"):
            scr = open(f"{outpath}", 'r')
            print(scr.read())


        
